#!/bin/sh
#

disk() {
	df --output=pcent . | tail -n 1 | tr -d '[:space:]|%'
}

backlight() {
	printf "%.0f\n" $(xbacklight -get)
}

wifi() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "󰤨" ;;
	down) printf "󰤭" ;;
	esac
}

"$@"
